# Generated by Django 2.2.17 on 2021-02-09 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choise',
            new_name='Choiсe',
        ),
        migrations.RenameField(
            model_name='choiсe',
            old_name='choise_text',
            new_name='choiсe_text',
        ),
    ]
