# Generated by Django 2.2.17 on 2021-02-09 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210209_2341'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choiсe',
            new_name='Choice',
        ),
    ]
